### ISSUE TITLE
Get Development Environment Setup

### ISSUE THREAD

**Issue by anttipessa** [anttipessa/vscode-python#11]
- Guide to get environment up and running can be found here https://github.com/microsoft/vscode-python/wiki/Coding.
- Coding guidelines for TypeScript https://github.com/microsoft/vscode-python/wiki/Contributing

**Comment by JeonCD** [comment]
Cloned the project enviroinment and inspected the code in VSCode.

**Comment by haalto** [comment]
Cloned project. Tried building the project but getting a lot of error. Also activating venv on Windows is pretty annoying. Try using Git Bash.

**Comment by anttipessa** [comment]
to finally create the build run command `npm run package`

**Comment by anttipessa** [comment]
Mypy wasn't working in the development version, moving back to in progress for now

**Comment by anttipessa** [comment]
Tested the build process and got it working. Everytime a new package is created, in VSC -> extensions -> install from VSIX
![image](https://user-images.githubusercontent.com/33652286/109016008-637e0880-76be-11eb-81ec-0dab9a553c6e.png)

**Comment by anttipessa** [comment]
Mypy not showing was venv related I think
