### ISSUE TITLE
Reproduce the bug

### ISSUE THREAD

**Issue by anttipessa** [anttipessa/vscode-python#8]
Expected behaviour
Error for undefined name 'foo' points at 'f' of 'foo' (the 19th character on the line in the example below)

Actual behaviour
Error points at first 'o' instead (the 20th character)

Steps to reproduce:
Configure both Pylance and mypy. Enter this code in a .py file:

def f(arg: int) -> int:
return (arg + foo + 1)
Hit F8 once to show the Pylance error pointing at 'f', and again to show the mypy error pointing at '

**Comment by anttipessa** [comment]
Expected behaviour
Error for undefined name 'foo' points at 'f' of 'foo' (the 19th character on the line in the example below)

Actual behaviour
Error points at first 'o' instead (the 20th character)

Steps to reproduce:
Configure both Pylance and mypy. Enter this code in a .py file:

def f(arg: int) -> int:
    return (arg + foo + 1)
Hit F8 once to show the Pylance error pointing at 'f', and again to show the mypy error pointing at '

**Comment by anttipessa** [comment]
Spend a hour trying to reproduce, couldn't get mypy working properly. Might be something wrong with my python installation.

**Comment by haalto** [comment]
![image.png](https://images.zenhubusercontent.com/601adc2702673f32f2cd3b5e/9055dd5d-9c37-48bc-a5d5-c12ba465ac47)

Tried to reproduce. Got only this message. Pylance and mypy should be ok.

**Comment by haalto** [comment]
![image.png](https://images.zenhubusercontent.com/601adc2702673f32f2cd3b5e/9ad7c67c-e2b5-4694-9f79-b5b943c8f46d)

Reproduced bug.

**Comment by haalto** [comment]
![image.png](https://images.zenhubusercontent.com/601adc2702673f32f2cd3b5e/b3977f2f-fce2-413b-a96f-1064dfee1855)
Reproduced bug.
